from mcp.server.fastmcp import FastMCP
from typing import Dict,Any,Optional
from ..core.decorators import log_tool_execution
import asyncio
import logging
import threading
from functools import wraps

client = None
logger = logging.getLogger(__name__)

def async_to_sync(async_func):
    """Utility decorator to convert async functions to sync with proper event loop handling."""
    @wraps(async_func)
    def wrapper(*args, **kwargs):
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # Create a task and run it synchronously
                result = None
                exception = None
                def run_in_thread():
                    nonlocal result, exception
                    try:
                        result = asyncio.run(async_func(*args, **kwargs))
                    except Exception as e:
                        exception = e
                thread = threading.Thread(target=run_in_thread)
                thread.start()
                thread.join()
                if exception:
                    raise exception
                return result
            else:
                return loop.run_until_complete(async_func(*args, **kwargs))
        except RuntimeError:
            return asyncio.run(async_func(*args, **kwargs))
    return wrapper

def make_api_request(method: str, endpoint: str, params: dict = None, json_body: dict = None):
    """Utility function to make API requests with consistent parameter handling."""
    @async_to_sync
    async def _make_request():
        return await client.make_request(method, endpoint, params=params or {}, json=json_body)
    return _make_request()

def build_params(**kwargs):
    """Build parameters dictionary excluding None values."""
    return {k: v for k, v in kwargs.items() if v is not None}

@log_tool_execution
def search_engines(limit: Optional[int] = None, cursor: Optional[str] = None, sort: Optional[str] = None, filter_expression: Optional[str] = None) -> Dict[str, Any]:
    """
    Search for engines.
    :param limit: Maximum number of objects to return per query. The value must be between 1 and 1000. Default is 100.
    :param limit: Maximum number of objects to return per query. The value must be between 1 and 1000. Default is 100.(optional)
    :param cursor: Cursor to fetch the next or previous page of results. The value of this property must be extracted from the 'prev_cursor' or 'next_cursor' property of a PaginatedResponseMetadata which is contained in the response of list and search API endpoints.
    :param cursor: Cursor to fetch the next or previous page of results. The value of this property must be extracted from the 'prev_cursor' or 'next_cursor' property of a PaginatedResponseMetadata which is contained in the response of list and search API endpoints.(optional)
    :param sort: The field to sort results by. A property name with a prepended '-' signifies descending order.
    :param sort: The field to sort results by. A property name with a prepended '-' signifies descending order.(optional)
    :param filter_expression: Filter expression string (optional)
    Filter expression can include the following fields:
     - id: The Engine object entity ID.
     - uuid: The unique identifier generated by this engine.
     - type: The type of this engine.
     - version: The engine version.
     - name: The name of this engine.
     - ssh_public_key: The ssh public key of this engine.
     - hostname: The hostname of this engine.
     - cpu_core_count: The total number of CPU cores on this engine.
     - memory_size: The total amount of memory on this engine, in bytes.
     - data_storage_capacity: The total amount of storage allocated for engine objects and system metadata, in bytes.
     - data_storage_used: The amount of storage used by engine objects and system metadata, in bytes.
     - insecure_ssl: Allow connections to the engine over HTTPs without validating the TLS certificate. Even though
the connection to the engine might be performed over HTTPs, setting this property eliminates
the protection against a man-in-the-middle attach for connections to this engine. Instead,
consider configuring DCT with Certificate Authority certificates.

     - unsafe_ssl_hostname_check: Ignore validation of the name associated to the TLS certificate when connecting to the engine over HTTPs.
Setting this value must only be done if the TLS certificate of the engine does not match the hostname,
and the TLS configuration of the engine cannot be fixed. Setting this property reduces the protection
against a man-in-the-middle attack for connections to this engine.
This is ignored if insecure_ssl is set.

     - status: the status of the engine

     - connection_status: The status of the connection to the engine. Deprecated; use "engine_connection_status" instead.
     - engine_connection_status: The state of the connection to the engine.
     - connection_status_details: If set, details about the status of the connection to the engine. Deprecated; use "engine_connection_status_details" instead.
     - engine_connection_status_details: If set, details about the state of the connection to the engine.
     - username: The virtualization domain admin username.
     - password: The virtualization domain admin password.
     - masking_username: The masking admin username.
     - masking_password: The masking admin password.
     - hashicorp_vault_username_command_args: Arguments to pass to the Vault CLI tool to retrieve the virtualization username for the engine.
     - hashicorp_vault_masking_username_command_args: Arguments to pass to the Vault CLI tool to retrieve the masking username for the engine.
     - hashicorp_vault_password_command_args: Arguments to pass to the Vault CLI tool to retrieve the virtualization password for the engine.
     - hashicorp_vault_masking_password_command_args: Arguments to pass to the Vault CLI tool to retrieve the masking password for the engine.
     - masking_hashicorp_vault_id: Reference to the Hashicorp vault to use to retrieve masking engine credentials.
     - hashicorp_vault_id: Reference to the Hashicorp vault to use to retrieve virtualization engine credentials.
     - tags: The tags to be created for this engine.
     - masking_memory_used: The current amount of memory used by running masking jobs in bytes.
     - masking_allocated_memory: The maximum amount of memory available for running masking jobs in bytes.
     - masking_jobs_running: The number of masking jobs currently running.
     - masking_max_concurrent_jobs: The maximum number of masking jobs that can be running at the same time.
     - masking_available_cores: The number of CPU cores available to the masking engine.
     - hyperscale_instance_ids: List of Hyperscale Instances that this engine is connected to.
     - hyperscale_truststore_filename: File name of a truststore which can be used to validate the TLS certificate of the engine as expected by associated hyperscale instances.

     - hyperscale_truststore_password: Password to read the truststore as expected by associated hyperscale instances.

     - using_object_storage: true if the engine is using an object store (like AWS S3) to store data |
false if the engine is using block storage to store its data |
null if the engine is not initialized (unlikely) or the engine API version does not provide that information

     - using_continuous_vault: true if the engine is using an object store (like AWS S3) to store data |
false if the engine is using block storage to store its data |
null if the engine is not initialized (unlikely) or the engine API version does not provide that information

     - platform: The infrastructure or environment where the engine is deployed or built, including cloud provider and instance type.
     - storage_cache_bytes: Total number of bytes of storage reserved for storage cache
     - priority_cache_max_bytes: Total number of bytes of storage available for VDB priority caching
     - priority_cache_used_bytes: Total number of bytes of storage allocated to existing priority cache enabled vdbs

    How to use filter_expresssion: 
    A request body containing a filter expression. This enables searching
    for items matching arbitrarily complex conditions. The list of
    attributes which can be used in filter expressions is available
    in the x-filterable vendor extension.
    
    # Filter Expression Overview
    **Note: All keywords are case-insensitive**
    
    ## Comparison Operators
    | Operator | Description | Example |
    | --- | --- | --- |
    | CONTAINS | Substring or membership testing for string and list attributes respectively. | field3 CONTAINS 'foobar', field4 CONTAINS TRUE  |
    | IN | Tests if field is a member of a list literal. List can contain a maximum of 100 values | field2 IN ['Goku', 'Vegeta'] |
    | GE | Tests if a field is greater than or equal to a literal value | field1 GE 1.2e-2 |
    | GT | Tests if a field is greater than a literal value | field1 GT 1.2e-2 |
    | LE | Tests if a field is less than or equal to a literal value | field1 LE 9000 |
    | LT | Tests if a field is less than a literal value | field1 LT 9.02 |
    | NE | Tests if a field is not equal to a literal value | field1 NE 42 |
    | EQ | Tests if a field is equal to a literal value | field1 EQ 42 |
    
    ## Search Operator
    The SEARCH operator filters for items which have any filterable
    attribute that contains the input string as a substring, comparison
    is done case-insensitively. This is not restricted to attributes with
    string values. Specifically `SEARCH '12'` would match an item with an
    attribute with an integer value of `123`.
    
    ## Logical Operators
    Ordered by precedence.
    | Operator | Description | Example |
    | --- | --- | --- |
    | NOT | Logical NOT (Right associative) | NOT field1 LE 9000 |
    | AND | Logical AND (Left Associative) | field1 GT 9000 AND field2 EQ 'Goku' |
    | OR | Logical OR (Left Associative) | field1 GT 9000 OR field2 EQ 'Goku' |
    
    ## Grouping
    Parenthesis `()` can be used to override operator precedence.
    
    For example:
    NOT (field1 LT 1234 AND field2 CONTAINS 'foo')
    
    ## Literal Values
    | Literal      | Description | Examples |
    | --- | --- | --- |
    | Nil | Represents the absence of a value | nil, Nil, nIl, NIL |
    | Boolean | true/false boolean | true, false, True, False, TRUE, FALSE |
    | Number | Signed integer and floating point numbers. Also supports scientific notation. | 0, 1, -1, 1.2, 0.35, 1.2e-2, -1.2e+2 |
    | String | Single or double quoted | "foo", "bar", "foo bar", 'foo', 'bar', 'foo bar' |
    | Datetime | Formatted according to [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) | 2018-04-27T18:39:26.397237+00:00 |
    | List | Comma-separated literals wrapped in square brackets | [0], [0, 1], ['foo', "bar"] |
    
    ## Limitations
    - A maximum of 8 unique identifiers may be used inside a filter expression.
    
    """
    # Build parameters excluding None values
    params = build_params(limit=limit, cursor=cursor, sort=sort)
    search_body = {'filter_expression': filter_expression}
    return make_api_request('POST', '/management/engines/search', params=params, json_body=search_body)


def register_tools(app, dct_client):
    global client
    client = dct_client
    logger.info(f'Registering tools for engine_endpoints...')
    try:
        logger.info(f'  Registering tool function: search_engines')
        app.add_tool(search_engines, name="search_engines")
    except Exception as e:
        logger.error(f'Error registering tools for engine_endpoints: {e}')
    logger.info(f'Tools registration finished for engine_endpoints.')
